### PR TITLE
added solar metallicity as flag for BSE

### PR DESCRIPTION
**Pull request by michaelzevin**
This is part of the BSEDict. Default value will be 0.017 (as in the example Params.ini), but I've set it to 0.02 for now to pass unit tests.

### CODE REVIEW

**Comment by michaelzevin** [comment]
@scottcoughlin2014 not sure why this didn't pass, any thoughts?

**Comment by katiebreivik** [comment]
Looks like the Travis build is failing for something in the docs. I'll check this out locally to see what's going on.

**Comment by katiebreivik** [comment]
Huh - looks like sphinx still isnt working on Travis; the docs built locally though...

It also looks like the benchmarkevolv2.f is running into an error

**Comment by michaelzevin** [comment]
@scottcoughlin2014 can you look into this when you have a chance? I updated benchmarkevolv2.f so not sure why it still isn't passing.

**Comment by katiebreivik** [comment]
I think I found a fix with the benchmarkevolve2.f; it's in a PR to your branch @michaelzevin

**Comment by michaelzevin** [comment]
Yay! Thanks for the catch @katiebreivik. Darn punctuation always gets me...

**Pull request merged**
