### PR TITLE
Added the ability to pass a path to the inifile contain the BSE flags…

### PR DESCRIPTION
**Pull request by scottcoughlin2014**
… in order to run evolve. Also I really revamped the logic of the three ways that one can pass the BSE flag information to Evolve.evolve through better documentation and clearer key word argument passing. Moreover in order to stop getting the pandas SettingWithCopyWarning I changed the way we assign the passed flags as columns to the DF. I think it is better and the warning will stop happening.

### CODE REVIEW

**Comment by michaelzevin** [comment]
@scottcoughlin2014 do you know why the unit test failed for this? I can't see why they would.

**Comment by scottcoughlin2014** [comment]
> Looks pretty good to me @scottcoughlin2014. Before approving, did you check that this works when you provide a Params.ini file? You should check this when (a) there are already flags set in the initial binary table and (b) when there are not flags set in the initial binary table.
> 
> Also, do the flags in the initialbinarytable always take precedence whether you specify a BSEDict or Params.ini?

Hey Mike,

In the two unit tests I added to `test_evolve` I have included all three scenarios including passing the `Params.ini` file (in fact the one that is in the `examples` folder).

Also in the doc strings I have added the answer
```
        NUMBER 2: PASS A PANDAS DATA FRAME WITH PARAMS DEFINED AS COLUMNS
             All you need is the initialbinarytable with columns,
             If you pass both a dictionary of flags and/or a inifile
             and a table with the columns, the column values for the flags
             take precedent
```

**Comment by scottcoughlin2014** [comment]
> @scottcoughlin2014 do you know why the unit test failed for this? I can't see why they would.

@michaelzevin Thisis related to the `porb` unit changes (see slack discussion) Once Katie does another PR to address it the unit tests should not fail (i.e. it fails for an unrelated reason)

**Comment by michaelzevin** [comment]
@scottcoughlin2014 per our discussion in the COSMIC meeting today, we are going to make 2 changes: 

1) if BSEDict or Params.ini are specified in the kwargs, they will take precedence over what is specified in the initialbinarytable. 
2) Add a warning if BSEDict or Params.ini are trying to overwrite a flag that is already set in initialbinarytable.

**Comment by scottcoughlin2014** [comment]
> @scottcoughlin2014 per our discussion in the COSMIC meeting today, we are going to make 2 changes:
> 
>     1. if BSEDict or Params.ini are specified in the kwargs, they will take precedence over what is specified in the initialbinarytable.
> 
>     2. Add a warning if BSEDict or Params.ini are trying to overwrite a flag that is already set in initialbinarytable.

@michaelzevin I have switched the logic of the ```kwargs``` and immensely cleaned up the logic of the code, far fewer lines and now when you want to add a flag to pass to BSE I think it will be easier.

**Pull request merged**
