### PR TITLE
changed ecsnp and ppsn flags

### PR DESCRIPTION
**Pull request by michaelzevin**
changed ecsnp flag to 'ecsn', changed ppsn flag to 'pisn'. now for pisn flag, a positive number will set the lower mass of the PPISN gap, 0 will turn off PISN, and -1 will apply formulae from Spera and Mapelli 2017

### CODE REVIEW

**Comment by scottcoughlin2014** [comment]
@michaelzevin `test_evolve` failed did you run the unit test locally?

**Comment by scottcoughlin2014** [comment]
@michaelzevin you did not over write the unit test file with the new logic of the flags

**Comment by michaelzevin** [comment]
What files should I look at to see if I did?

**Comment by scottcoughlin2014** [comment]
`ls cosmic//tests/data/initial_conditions_for_testing.hdf5`

**Comment by michaelzevin** [comment]
@scottcoughlin2014 can you point me to where this other doc thing is? I can't see where it would be in index.rst

**Comment by scottcoughlin2014** [comment]
These are the two place and you changed it in one @michaelzevin 
```
docs/runpop/index.rst:146:    In [4]: BSEDict = {'xi': 0.5, 'bhflag': 1, 'neta': 0.5, 'windflag': 3, 'wdflag': 0, 'alpha1': 1.0, 'pts1': 0.05, 'pts3': 0.02, 'pts2': 0.01, 'epsnov': 0.001, 'hewind': 1.0, 'ck': -1000, 'bwind': 0.0, 'lambdaf': 1.0, 'mxns': 3.0, 'beta': -1.0, 'tflag': 1, 'acc2': 1.5, 'nsflag': 3, 'ceflag': 0, 'eddfac': 1.0, 'merger': 0, 'ifflag': 0, 'bconst': -3000, 'sigma': 265.0, 'gamma': -2.0, 'ppsn': 1, 'natal_kick_array' :[-100.0,-100.0,-100.0,-100.0,-100.0,-100.0], 'bhsigmafrac' : 1.0, 'polar_kick_angle' : 90, 'qcrit_array' : [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0], 'cekickflag' : 0, 'cehestarflag' : 0, 'cemergeflag' : 0, 'ecsnp' : 2.5, 'ecsn_mlow' : 1.6, 'aic' : 1, 'sigmadiv' :-20.0}
docs/examples/index.rst:72:    In [5]: BSEDict = {'xi': 0.5, 'bhflag': 1, 'neta': 0.5, 'windflag': 3, 'wdflag': 0, 'alpha1': 1.0, 'pts1': 0.001, 'pts3': 0.02, 'pts2': 0.01, 'epsnov': 0.001, 'hewind': 1.0, 'ck': -1000, 'bwind': 0.0, 'lambdaf': 1.0, 'mxns': 3.0, 'beta': -1.0, 'tflag': 1, 'acc2': 1.5, 'nsflag': 3, 'ceflag': 0, 'eddfac': 1.0, 'merger': 0, 'ifflag': 0, 'bconst': -3000, 'sigma': 265.0, 'gamma': -2.0, 'ppsn': 1, 'natal_kick_array' : [-100.0,-100.0,-100.0,-100.0,-100.0,-100.0], 'bhsigmafrac' : 1.0, 'polar_kick_angle' : 90, 'qcrit_array' : [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0], 'cekickflag' : 0, 'cehestarflag' : 0, 'cemergeflag' : 0, 'ecsnp' : 2.5, 'ecsn_mlow' : 1.6, 'aic' : 1, 'sigmadiv' :-20.0}
```

**Comment by michaelzevin** [comment]
@scottcoughlin2014 ok added it. let me know if this works.

**Comment by scottcoughlin2014** [comment]
```
gfortran:f77: cosmic/src/bpp_array.f
const_bse.h:20:21: Warning: Padding of 4 bytes required before ‘pisn’ in COMMON ‘value1’ at (1); reorder elements or use -fno-align-commons
const_bse.h:20:21: Warning: Padding of 4 bytes required before ‘pisn’ in COMMON ‘value1’ at (1); reorder elements or use -fno-align-commons
gfortran:f77: build/src.linux-x86_64-3.7/cosmic/_evolvebin-f2pywrappers.f
build/src.linux-x86_64-3.7/cosmic/_evolvebin-f2pywrappers.f:567:21:
       common /value1/ neta,bwind,hewind,mxns,windflag,pisn
                     1
Warning: Padding of 4 bytes required before ‘pisn’ in COMMON ‘value1’ at (1); reorder elements or use -fno-align-commons
```
I do *not* like the `pisn` padding common variable warnings that are popping up. Can you fix this? You should be able to know this by compiling locally until the warning go away

**Pull request closed without merging**
