### PR TITLE
Eddlim patch

### PR DESCRIPTION
**Pull request by michaelzevin**

### CODE REVIEW

**Comment by michaelzevin** [comment]
shoot...forgot I did the cehestar changes on develop. We should merge that one first.

**Comment by katiebreivik** [comment]
@michaelzevin since @scottcoughlin2014 is off for the weekend, do you mind if I review and we can get this merged?

**Comment by michaelzevin** [comment]
@katiebreivik go for it, it will take 2 seconds.

**Comment by michaelzevin** [comment]
But we'll likely want to merge the cehestarflag PR first

**Comment by katiebreivik** [comment]
> But we'll likely want to merge the cehestarflag PR first

I did this morning

**Pull request merged**
