### PR TITLE
WIP: First pass at handling filtering through the ini file. 

### PR DESCRIPTION
**Pull request by scottcoughlin2014**
I have not tackled convergence at all except there is a line in the inifile.

### CODE REVIEW

**Comment by scottcoughlin2014** [comment]
@katiebreivik I would checkout this branch i.e. you can literally chekcout this PR in GIT and then add stuff to it and you can commit to it and stuff

**Comment by scottcoughlin2014** [comment]
@katiebreivik great! in general there is the view command line instructions that helps!

**Comment by katiebreivik** [comment]
@scottcoughlin2014  I think I pushed some commits (including tests for the new code in utils) to your branch but maybe you need to open a new pr?

**Comment by scottcoughlin2014** [comment]
@katiebreivik I accepted you PR into this branch on my fork of the code and so your commits show up here, thanks for adding a convergence utilities function and some unit tests. I will pull this locally and muck about with it a bit but think it is coming together. definitely cleaning up some of the lines of `runfixedPop` if nothing else.

**Comment by katiebreivik** [comment]
@scottcoughlin2014 : I am inclined to merge this so we can get things back to the develop branch. Then I can add in the tests we talked about. I also agree that we need to have some special cases for the match re: https://github.com/COSMIC-PopSynth/COSMIC/issues/92#issue-391390374

but I'm wondering if this will mess up your PRs? re: https://github.com/COSMIC-PopSynth/COSMIC/issues/93#issuecomment-447587840

What do you you think?

**Comment by scottcoughlin2014** [comment]
@katiebreivik If you think you could merge this branch (which also has the change to the threading code coincidentally) and I have been running it on quest and this is super fast. If you merge this into develop and can make a brach immediately called updated-unit-tests and we can get that knock out by tuesday that would be good. This PR probably has WAY too much stuff in it relative to what it should but i think just getting it merged like you said will make the minor changes we make in the upcoming PRs easier and better

**Pull request merged**
